USE [master]
GO
CREATE DATABASE [EVDashboard] ON  PRIMARY 
( NAME = N'EVDashboard', FILENAME = N'D:\MSSQL\DATA\EVDashboard.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EVDashboard_log', FILENAME = N'D:\MSSQL\LOGS\EVDashboard_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE Latin1_General_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'EVDashboard', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EVDashboard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EVDashboard] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EVDashboard] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EVDashboard] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EVDashboard] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EVDashboard] SET ARITHABORT OFF 
GO
ALTER DATABASE [EVDashboard] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EVDashboard] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [EVDashboard] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EVDashboard] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EVDashboard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EVDashboard] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EVDashboard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EVDashboard] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EVDashboard] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EVDashboard] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EVDashboard] SET  ENABLE_BROKER 
GO
ALTER DATABASE [EVDashboard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EVDashboard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EVDashboard] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EVDashboard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EVDashboard] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EVDashboard] SET  READ_WRITE 
GO
ALTER DATABASE [EVDashboard] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EVDashboard] SET  MULTI_USER 
GO
ALTER DATABASE [EVDashboard] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EVDashboard] SET DB_CHAINING OFF 